<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../BusinessOS.Restaurant.Authentication/BusinessOS.Restaurant.Authentication.csproj" />
    <ProjectReference Include="../BusinessOS.Restaurant.Licensing/BusinessOS.Restaurant.Licensing.csproj" />
    <ProjectReference Include="../BusinessOS.Restaurant.Persistence/BusinessOS.Restaurant.Persistence.csproj" />
  </ItemGroup>
</Project>
