using BusinessOS.Restaurant.Persistence;
using Microsoft.EntityFrameworkCore;

namespace BusinessOS.Restaurant.LocalServer;

/// <summary>
/// Explicit local-only maintenance operations for a signed standalone restaurant.
/// Historical operational/financial rows are never deleted or rewritten.
/// No cloud outbox mutations are generated by this service.
/// </summary>
public sealed class StandaloneCatalogService(LocalDatabaseFactory factory)
{
    public async Task UpdateDishAsync(
        string id, string name, decimal priceAfn, bool available,
        string? sku, string actorRole, CancellationToken token = default)
    {
        EnsureManager(actorRole);
        var normalized = name.Trim();
        if (normalized.Length is < 2 or > 180 || priceAfn is < 0 or > 1_000_000)
            throw new ArgumentException("Enter a dish name and AFN price within permitted limits.");

        var code = string.IsNullOrWhiteSpace(sku) ? null : sku.Trim();
        if (code?.Length > 80) throw new ArgumentException("SKU is too long.", nameof(sku));

        await factory.EnsureCreatedAsync(token);
        await using var db = factory.Create();
        await using var tx = await db.Database.BeginTransactionAsync(token);
        var dish = await db.MenuItems.SingleOrDefaultAsync(x => x.Id == id, token)
            ?? throw new InvalidOperationException("The dish does not exist.");
        if (code is not null && await db.MenuItems.AnyAsync(x => x.Id != id && x.Sku == code, token))
            throw new InvalidOperationException("Another dish already uses this SKU.");

        dish.Name = normalized;
        dish.Price = priceAfn;
        dish.IsAvailable = available;
        dish.Sku = code;
        await db.SaveChangesAsync(token);
        await tx.CommitAsync(token);
    }

    public async Task UpdateTableAsync(
        string id, string name, int seats, bool active,
        string actorRole, CancellationToken token = default)
    {
        EnsureManager(actorRole);
        if (string.IsNullOrWhiteSpace(name) || name.Trim().Length > 120 || seats is < 1 or > 50)
            throw new ArgumentException("Table name or number of seats is invalid.");

        await factory.EnsureCreatedAsync(token);
        await using var db = factory.Create();
        await using var tx = await db.Database.BeginTransactionAsync(token);
        var table = await db.DiningTables.SingleOrDefaultAsync(x => x.Id == id, token)
            ?? throw new InvalidOperationException("The table does not exist.");
        if (!active && table.IsActive)
        {
            if (table.Status != "available" ||
                await db.Orders.AnyAsync(x => x.DiningTableId == id &&
                    x.Status != "closed" && x.Status != "cancelled", token))
                throw new InvalidOperationException(
                    "An occupied, reserved or financially unsettled table cannot be disabled.");
        }

        table.Name = name.Trim();
        table.Capacity = seats;
        table.IsActive = active;
        await db.SaveChangesAsync(token);
        await tx.CommitAsync(token);
    }

    public async Task UpdateCategoryAsync(
        string id, string name, bool active,
        string actorRole, CancellationToken token = default)
    {
        EnsureManager(actorRole);
        if (string.IsNullOrWhiteSpace(name) || name.Trim().Length > 120)
            throw new ArgumentException("Category name is invalid.");

        await factory.EnsureCreatedAsync(token);
        await using var db = factory.Create();
        var category = await db.MenuCategories.SingleOrDefaultAsync(x => x.Id == id, token)
            ?? throw new InvalidOperationException("Category not found.");
        if (await db.MenuCategories.AnyAsync(x => x.Id != id && x.Name == name.Trim(), token))
            throw new InvalidOperationException("Another category already uses this name.");
        category.Name = name.Trim();
        category.IsActive = active;
        // Existing dish and order history is preserved.
        await db.SaveChangesAsync(token);
    }

    public async Task<string> UpsertKitchenStationAsync(
        string? id, string branchId, string code, string name,
        string actorRole, CancellationToken token = default)
    {
        EnsureManager(actorRole);
        code = code.Trim().ToUpperInvariant();
        name = name.Trim();
        if (code.Length is < 1 or > 30 || name.Length is < 2 or > 120)
            throw new ArgumentException("Enter a kitchen station code and name.");

        await factory.EnsureCreatedAsync(token);
        await using var db = factory.Create();
        await using var tx = await db.Database.BeginTransactionAsync(token);
        if (!await db.Branches.AnyAsync(x => x.Id == branchId && x.IsActive, token))
            throw new InvalidOperationException("Select an active branch.");

        var station = id is null ? null :
            await db.KitchenStations.SingleOrDefaultAsync(x => x.Id == id, token);
        if (id is not null && station is null) throw new InvalidOperationException("Station not found.");
        if (station is not null && station.BranchId != branchId)
            throw new InvalidOperationException("Moving a kitchen station between branches is not permitted.");
        if (await db.KitchenStations.AnyAsync(x => x.BranchId == branchId &&
            x.Code == code && x.Id != id, token))
            throw new InvalidOperationException("Station code already exists in this branch.");

        if (station is null)
        {
            station = new LocalKitchenStation
            {
                Id = Guid.CreateVersion7().ToString("N"), BranchId = branchId,
                Code = code, Name = name, SortOrder = 0, IsActive = true,
            };
            db.KitchenStations.Add(station);
        }
        else
        {
            station.Name = name;
            station.Code = code;
        }
        await db.SaveChangesAsync(token);
        await tx.CommitAsync(token);
        return station.Id;
    }

    public async Task RouteDishToStationAsync(
        string dishId, string branchId, string stationId,
        string actorRole, CancellationToken token = default)
    {
        EnsureManager(actorRole);
        await factory.EnsureCreatedAsync(token);
        await using var db = factory.Create();
        await using var tx = await db.Database.BeginTransactionAsync(token);

        if (!await db.MenuItems.AnyAsync(x => x.Id == dishId && x.IsAvailable, token))
            throw new InvalidOperationException("Select an available dish.");
        if (!await db.KitchenStations.AnyAsync(x => x.Id == stationId &&
            x.BranchId == branchId && x.IsActive, token))
            throw new InvalidOperationException("Kitchen station must be active and in the selected branch.");

        var existing = await db.MenuItemKitchenRoutes
            .SingleOrDefaultAsync(x => x.MenuItemId == dishId && x.BranchId == branchId, token);
        if (existing is null)
        {
            db.MenuItemKitchenRoutes.Add(new LocalMenuItemKitchenRoute
            {
                Id = Guid.CreateVersion7().ToString("N"), MenuItemId = dishId,
                BranchId = branchId, KitchenStationId = stationId,
            });
        }
        else
            existing.KitchenStationId = stationId;

        await db.SaveChangesAsync(token);
        await tx.CommitAsync(token);
    }

    private static void EnsureManager(string actorRole)
    {
        if (actorRole.Trim().ToLowerInvariant() is not ("owner" or "admin" or "manager"))
            throw new UnauthorizedAccessException("Only a restaurant manager can edit the local catalog.");
    }
}
